flags = "menu"
FPS = 60
WHITE = 255, 255, 255
BLACK = 0, 0, 0
W, H = 864, 768
bg = "flappy/img/bg.png"
bird_img = "flappy/img\yellowbird-midflap.png"
platform = "flappy/img/ground.png"
pipe_green = "flappy/img/pipe-green.png"
message = "flappy/img/message.png"
gameover = "flappy/img/gameover.png"
sound_die = "flappy/sound/die.ogg"
sound_hit = "flappy/sound/hit.ogg"
sound_wing = "flappy/sound/wing.ogg"
sound_point = "flappy/sound/point.ogg"
score_img = ["flappy/img/score/0.png", "flappy/img/score/1.png", "flappy/img/score/2.png", "flappy/img/score/3.png", "flappy/img/score/4.png", "flappy/img/score/5.png", "flappy/img/score/6.png", "flappy/img/score/7.png", "flappy/img/score/8.png", "flappy/img/score/9.png"]